esphome:
  name: sd-card-arduino

esp32:
  # ESP32-S3 N16R8 Type-C Development Board
  board: 4d_systems_esp32s3_gen4_r8n16
  framework:
    type: arduino
    advanced:
      disable_vfs_support_termios: false
      disable_vfs_support_select: false
      disable_vfs_support_dir: false

external_components:
  - source: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: VERBOSE

sd_mmc_card:
  id: sd_card
  mode_1bit: true
  format_if_mount_failed: true
  clk_pin:
    number: 12
  cmd_pin:
    number: 11
  data0_pin:
    number: 13
  data3_pin:
    number: 10

button:
  - platform: template
    name: "Test Full SD Card Operations"
    on_press:
      then:
        - sd_mmc_card.write_file:
            path: "/test.txt" 
            data: !lambda |
              std::string str("content");
              return std::vector<uint8_t>(str.begin(), str.end());
        - logger.log: "file saved"
        - sd_mmc_card.delete_file:
            path: "/test.txt"
        - logger.log: "file deleted"
        - sd_mmc_card.create_directory:
            path: "/test_dir"
        - logger.log: "directory created"
        - sd_mmc_card.remove_directory:
            path: "/test_dir"
        - logger.log: "directory removed"

  - platform: template
    name: "Test Create"
    on_press:
      then:
        - sd_mmc_card.write_file:
            path: "/test.txt" 
            data: !lambda |
              std::string str("content");
              return std::vector<uint8_t>(str.begin(), str.end());
        - logger.log: "file saved"
        - sd_mmc_card.create_directory:
            path: "/test_dir"
        - logger.log: "directory created"

sensor:
  - platform: sd_mmc_card
    type: used_space
    unit_of_measurement: Mb
    name: "SD card used space"
    filters:
      - lambda: return sd_mmc_card::convertBytes(x, sd_mmc_card::MemoryUnits::MegaByte);

  - platform: sd_mmc_card
    type: total_space
    name: "SD card total space"
    unit_of_measurement: Gb
    filters:
      - lambda: return sd_mmc_card::convertBytes(x, sd_mmc_card::MemoryUnits::GigaByte);

  - platform: sd_mmc_card
    type: free_space
    name: "SD card free space"
    unit_of_measurement: Gb
    filters:
      - lambda: return sd_mmc_card::convertBytes(x, sd_mmc_card::MemoryUnits::GigaByte);

  - platform: sd_mmc_card
    type: file_size
    name: "text.txt size"
    unit_of_measurement: Kb
    path: "/test.txt"
    filters:
      - lambda: return sd_mmc_card::convertBytes(x, sd_mmc_card::MemoryUnits::KiloByte);

text_sensor:
  - platform: sd_mmc_card
    sd_card_type:
      name: "SD card type"

web_server:

sd_file_server:
  id: file_server
  url_prefix: "file"
  root_path: "/"
  enable_deletion: true
  enable_download: true
  enable_upload: true
